### ISSUE TITLE
Version 0.2.0 Crash

### ISSUE THREAD

**Issue by GHLurker** [VeryBaddude/plugin.video.curiositystream#5]
Initially I installed the latest version 0.2.0 from this repository, and it would not run.
I found the older version 0.1.0 at:
https://github.com/CuriosityProjectLLC/plugin.video.curiositystream
The older version runs just fine on Kodi Leia on a RPi3 with Estuary Mod skin.
Version 0.2.0, which I would like to install for the watchlist feature gives the following error from the log:

> 21:25:05.882 T:139746192914176   ERROR: Previous line repeats 8 times.
21:25:05.882 T:139746192914176   ERROR: GetDirectory - Error getting
21:25:08.279 T:139746424649472   ERROR: Previous line repeats 20 times.
21:25:08.279 T:139746424649472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'image_show'
                                            Traceback (most recent call last):
                                              File "/home/username/.kodi/addons/plugin.video.curiositystream/addon.py", line 356, in <module>
                                                list_categories(token)
                                              File "/home/username/.kodi/addons/plugin.video.curiositystream/addon.py", line 167, in list_categories
                                                debug('Setting art to ' + group['media'][0]['image_show'])
                                            KeyError: 'image_show'
                                            -->End of Python script error report<--
21:25:08.387 T:139746223322880   ERROR: GetDirectory - Error getting plugin://plugin.video.curiositystream/
21:25:08.394 T:139746938516352   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.curiositystream/) failed

Help?

**Comment by GHLurker** [comment]
BTW, that log entry was taken from a Kodi installation on an Ubuntu 18.10 machine. Same error on both RPi3 Libreelec Leia and desktop Kodi install.

**Comment by Blackneron** [comment]
I have the same problem...

**Comment by twmobius** [comment]
The `image_show` attribute does not exist in the response of the API so changing at lines 167-172

https://github.com/VeryBaddude/plugin.video.curiositystream/blob/2100b408d22c7d7ea390a834f285e4b6389ea916/addon.py#L167

where it says `image_show` to `image_small` should do the trick
